### PR TITLE
OPERATION CATBOX

### PR DESCRIPTION
**Pull request by NanoCats**
Wheeeee

# About The Pull Request / Why It's Good For The Game

God, I sure do fucking revile box station, let's change that shall we? When I started this PR it was a humble change to Engineering's foyer, but now I've committed to fully restyling the ENTIRETY of boxstation

## Testing Photographs and Procedure

<summary>Screenshots&Videos</summary>

image
image
image
image
image
image
image

## Changelog

:cl:
add: Brand New engineering lobby on Boxstation
add: Firelock window shutters added to select windows on Boxstation
add: Quartermaster's office expansion
add: Departures VIP lounge WOOOO
add: Literally thousands of decals, when I close my eyes I CAN ONLY SEE TRIMLINES HELP
add: Complete armoury replacement
add: Complete robotics replacmeent
add: Vital equipment for Cargo Techs and Virologists added to their respective departments
add: Completely redesigned bridge and public park
tweak: more decals in ~~cargo~~, everywhere but largely unchanged
tweak: AI upload and gravity generator redesigned and relocated
fix: Places plating to get rid of a mysterious hole at x199 y137 (evac)
fix: Adds a cargo console to cargo in the standard spot, how did these guys survive without one

/:cl:

### CODE REVIEW

**Comment by NanoCats** [comment]
I don't fucking know what 

`_maps/map_files/BoxStation/BoxStation.dmm:	pixel_x = 0;
ERROR: pixel_x/pixel_y = 0 variables detected in maps, please review to ensure they are not dirty varedits.` means or how to fix it, this is the least helpful fucking error imaginable

**Comment by NanoCats** [comment]
I think in the engineering hallway
I moved an APC with the eye dropper and just
pixel shifted it where I wanted it to be

It worked just fine, and the fact that this caused an error pisses me off immensely.

**Comment by nednaZ** [comment]
I have set this to draft as this isn't ready to review

**Comment by NanoCats** [comment]
> I have set this to draft as this isn't ready to review

You know, I was literally about to do that, I was just still editing the post when you bonked it lol.

**Comment by polygoblyn** [comment]
Litterbox is a better name

**Comment by NanoCats** [comment]
Federal regulations require me to warn you that this next test chamber... _is looking pretty good_.

**Comment by DoctorSquishy** [comment]
image
 Doing the area like this has the airlock controllers work in that sec area. Airlocks are weird code. They just work.

**Comment by NanoCats** [comment]
Recent commit adds fireaxe to the bridge

**Comment by nednaZ** [comment]
Developer stated that they are stopping work on this for the time being.
They may request this to be reopened at a later date.

**Comment by NanoCats** [comment]
I hate github sometimes

**Comment by NanoCats** [comment]
holy fuck why did it force me to do that.

**Pull request merged**
