### PR TITLE
Bee Updates 7-2-2022

### PR DESCRIPTION
**Pull request by DoctorSquishy**
# About The Pull Request
Some more applicable Bee updates

## Why It's Good For The Game
1. https://github.com/BeeStation/BeeStation-Hornet/pull/7114
2. https://github.com/BeeStation/BeeStation-Hornet/pull/7140 (They did an oopsies)
3. https://github.com/BeeStation/BeeStation-Hornet/pull/7115
4. https://github.com/BeeStation/BeeStation-Hornet/pull/7117
5. https://github.com/BeeStation/BeeStation-Hornet/pull/7120
6. https://github.com/BeeStation/BeeStation-Hornet/pull/7129
7. https://github.com/BeeStation/BeeStation-Hornet/pull/7131
8. https://github.com/BeeStation/BeeStation-Hornet/pull/7135
9. https://github.com/BeeStation/BeeStation-Hornet/pull/7141
10. https://github.com/BeeStation/BeeStation-Hornet/pull/7155
11. https://github.com/BeeStation/BeeStation-Hornet/pull/7052
12. https://github.com/BeeStation/BeeStation-Hornet/pull/7076

## Testing Photographs and Procedure
Click each PR for images and additional information

## Changelog

:cl: Dejaku51, Mothblocks, LemonInTheDark, Penwin0, EvilDragonfiend, covertcorvid, Miliviu, Rukofamicom
fix: Fixes /mob/dead/new_player harddels
fix: fixes some harddels
add: silicons no longer can state laws while they're stating laws.
fix: stating laws counts to the spam filter less than before. But do not spam stating laws, it still counts, but less.
fix: Incorporeal mobs can traverse Z levels through the floor/ceiling
tweak: Warnings about being unable to Z travel in gravity will only appear on space or openspace
tweak: Reverses animation direction for Z travel
spellcheck: Corrected a typo in the description of the Metal Upa plush
remove: Yiff in Hell Decal
tweak: spraying big decals has delay
fix: fixed Zombie Powder spamming the Death Gasp emote
tweak: Chief Engineers, Chief Medical Officers and Research Directors will no longer be accosted by security bots for owning their officially assigned sidearms.
balance: Voice of God stuns have been reduced substantially.
tweak: Due to language proficiency, the curator now gets a bonus when using the voice of God, but it is weaker than the one the chaplain already got.
tweak: Command staff and mimes no longer receive any positive bonus multipliers when utilizing the voice of god.
fix: fixed a forgotten equip-delay bypass on a hud element.
/:cl:

### CODE REVIEW

**Comment by NiftyRyanyan** [comment]
Why is added a 3 second delay to large sprays and removing the “yiff in hell” spray a good for the game?

**Comment by EvilDragonfiend** [comment]
> Why is added a 3 second delay to large sprays and removing the “yiff in hell” spray good for the game?

You can't say `remove the yiff` ICly due to the filter, as far as I heard.

**Comment by nednaZ** [comment]
> You can't say `remove the yiff` ICly due to the filter, as far as I heard.

We don't have that word as a filtered word here, thankfully not common enough to require it

**Review by nednaZ — APPROVED** [review]
Looks good, though I'll miss the instant spray paint.

**Pull request merged**
