### PR TITLE
Removes Annoying Ambimalf AI ambience

### PR DESCRIPTION
**Pull request by WonderPsycho**
just a quick PR doing just that

# About The Pull Request

removes the ambimalf.ogg ambience from Monke code

## Why It's Good For The Game

helps AI players to relax more without a annoying ai ambience constantly playing here and there while they do AI stuff

## Changelog

:cl:WonderPsycho
del: Removes Ambimalf.ogg and certain inclusions of forcing the line to play said now removed .ogg file
/:cl:

### CODE REVIEW

**Comment by Blueturbo47** [comment]
I'm pretty sure this is used when malf ai status is gained

**Comment by WonderPsycho** [comment]
> I'm pretty sure this is used when malf ai status is gained
> 
> Failed checks anyway

no last i checked it's malf.ogg that's the sound that's played when ai is malf for the ai's end, ambimalf.ogg, is only played when you the AI or you as a non-AI character like a cyborg or crew member, is in the AI's satelite or in the AI upload, it always plays that constantly for the AI cause the AI is in their satelite, and cause of how many AI players are annoyed by this ound playing constantly when they play AI, i decided to do a quick PR removing it, also just fixed up the failed checks by removing the stuff the files forcing it to play were doing cause i removed the sound file from the PR and stuff but yeah

**Comment by WonderPsycho** [comment]
also Zanden confirmed to me that Ambimalf is the file that constantly plays when in a AI area

**Comment by WonderPsycho** [comment]
> Please set up the changelog to reflect this change.

sorry i haven't been doing that problem is i don't know how to add a changelog thing about this

**Review by nednaZ — APPROVED** [review]

**Pull request merged**
