### PR TITLE
Ports shaken drinks from paradise.

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Ports the ability to shake drinks from paradise if shaken to much they will foam their contents on opening, or if done to much will explode foaming instantly. 
Also makes all drinks need to be opened before you can drink from them.
Adds the ability to reseal drinks for gimmicks.

## Why It's Good For The Game
It allows for some funny bar gimmicks and RP with the ability to give someone a shaken drink. Or a impromptu foaming container if resealed 

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Beer exploding on open

FoundBeer

Me shaking a beer than opening it

beershake

Me overshaking a beer and it exploding

overshke

</details>

## Changelog

:cl:
add: resealing option for drinks
add: shaken option for drinks
add: opening to other drinks aside from soda
/:cl:

### CODE REVIEW

**Review by nednaZ — COMMENTED** [review]
Drinking glasses can be shaken up and have to be popped open, despite being a clearly open-topped container

**Review by nednaZ — COMMENTED** [review]
There should be a description on a shaken can that says it has been shaken up.
"This container looks under pressure", some form of warning.

**Comment by dwasint** [comment]
>Drinking glasses can be shaken up and have to be popped open, despite being a clearly open-topped container
whoops missed that one fixed now

>There should be a description on a shaken can that says it has been shaken up.
"This container looks under pressure", some form of warning.

Gotcha added that aswell as a warning

**Review by nednaZ — APPROVED** [review]
I imagine this will lead to some balancing issues down the line, but I am willing to try it.

**Pull request merged**
