### PR TITLE
Box moment

### PR DESCRIPTION
**Pull request by NanoCats**
# About The Pull Request

Accidentally pulped another PR by accident by not updating my branch when making fixes 

For the record I think this is a bad change. That area is never going to be used to observe anything. Might as well have just gone whole hog and made it a hallway, because it's functionally just a hallway now. 

## Why It's Good For The Game

It's not; this PR makes me very upset and was made under duress. 

## Images

image

## Changelog

:cl:

add: Things from a PR that was accidentally atomized
fix: missing disposal pipes, door embedded in wall

/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
Review is left up to @KoboldCommando as this is their PR that was previously approved.
When it's back to the state they originally had it in, it will be merged.

**Comment by nednaZ** [comment]
You will need to unblock them here so that they may review.

**Review by KoboldCommando — CHANGES_REQUESTED** [review]
Looking at the changes made from the original PR, cigarettes make very little sense to me in a medical storage room, I would get rid of those and the matches.  If you're attached to them you could move them to one of the lounge tables outside.

This medbay already has a ton of wrenches as well.  Thinking about other items you could place on that table instead, a health analyzer and/or basic medkit would be nice, especially for the case where you get into that room but don't have windoor access.  A stethoscope would also be appropriate I think.

The extra set of windoors seems ok, if a bit niche in cases they'd be necessary. Similar with the techfab, it looks like it may cause some minor traffic issues moved forward like that, but I think it should be fine.

For the surgery door, you added an unrestricted access helper, but the door itself has no access requirement (which could actually be a mistake on my part in the original PR, oops!).  I would set the door access to 5 so not just anyone can wander in.

If you move/replace the added table clutter and fix the door access, I'm happy with this!

**Comment by NanoCats** [comment]
It's done

**Review by KoboldCommando — APPROVED** [review]
Looks good to me! Thanks for fixing it.

**Comment by nednaZ** [comment]
Approved by original creator.
After merge, make sure you update your master so we don't get another overwrite!

**Pull request merged**
