### PR TITLE
Docks and nested shuttles & Removes some major sleepers (100% lag free)

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
also reverts updates our mc to tg's as its needed for this
https://github.com/BeeStation/BeeStation-Hornet/pull/7152
https://github.com/BeeStation/BeeStation-Hornet/pull/7659

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: Nested shuttles. shuttles can now land on top of each other and be towed around.
add: Dock turfs. Shuttles can always land on these, regardless of whether the dock is in space, on the station, or on another shuttle. Tiles are craftable with 1 plasteel per 4 tiles.
add: Dry docks. Works like docks, but you can build on these as if you were in space and designate what you build onto a shuttle. Tiles are craftable with 2 plasteel per 4 tiles.
tweak: Arrival shuttles and Emergency shuttles cannot be towed by other shuttles.
refactor: Lots of changes to shuttle code, especially relating to docking.
balance: Machinery now blocks custom docking to prevent theft of important equipment.
/:cl:

### CODE REVIEW

**Comment by PowerfulBacon** [comment]
The MC changes aren't necessarilly required, the only MC changes made are for debugging purposes

**Comment by dwasint** [comment]
yea but i think they cause lag like you were saying previously

**Comment by PowerfulBacon** [comment]
ah

**Review by nednaZ — APPROVED** [review]
The master controller stuff is getting beyond my own knowledge here, but I'm going to trust that the Bee devs know what they're doing there.
Will attempt a testmerge and we'll watch for bugs to report back upstream.

**Comment by nednaZ** [comment]
Getting errors upon attempting to land the shuttle at a custom location:
```
ADMIN LOG: Shuttle Exploration Shuttle cannot dock at the custom location, error: 
```

**Comment by dwasint** [comment]
> Getting errors upon attempting to land the shuttle at a custom location:
> 
> ```
> ADMIN LOG: Shuttle Exploration Shuttle cannot dock at the custom location, error: 
> ```

fuck i thought i had fixed this issue, un-tm for now its something else that i gotta fix

**Comment by PowerfulBacon** [comment]
> I'm going to trust that the Bee devs know what they're doing there.

Brave assumption :trollface:

**Comment by nednaZ** [comment]
Dock tiles have no icon

**Comment by nednaZ** [comment]
Look into the "Multiple Pods" shuttle, it may have issues with this as it no longer spawns correctly.

**Comment by dwasint** [comment]
No more issues reported after last fix, seems ready to merge merging now.

**Pull request merged**
