### PR TITLE
PTSD: Now standard issue for all heads of staff [PORT]

### PR DESCRIPTION
**Pull request by DoctorSquishy**
# About The Pull Request
To quote the Bee PR:

> "All heads may acquire their PTSD by checking their locker for it, except for the HoS who starts the round with PTSD regardless of choice. The Captain and HoS may also find that their full size Energy Guns have been swapped out for PTSD (Not their unique guns, they still have these) and the other heads will find that their telescopic batons are no longer capable of inflicting stamcrit. Telescopic batons are still useful for tripping and disarming.
> 
> The gun in question is a modified version of the HoP's existing miniature energy gun. Modifications include 3 fewer disabler shots per charge and slow self-charging capabilities at the expense of being able to use recharging stations.
> 
> Has a flashlight built in, 12 disabler shots per full charge, 6 lethal shots per full charge, 120 seconds to reach full charge (regaining 2 disabler or 1 lethal every ten seconds). The gun may not use recharges and must slowly recharge on its own. 

**Note:** The gun starts in Head of Staffs bag instead, as requested from Maintainer.

## Why It's Good For The Game
To quote the Bee PR:

> "Even with most shifts being canonically peaceful, Nanotrasen is well aware that it does have enemies and it makes sense that all upper level members of staff would be issued a small arm for self-defense. This helps bring the heads of staff that otherwise only really had a baton before (CE, CMO, RD) up to a more reasonable level of self-defense.
> 
> The telescopic baton has has lost its ability to inflict stamcrit to make up for the increased overall firepower. However this also means that heads can no longer keep someone in stamcrit indefinitely since the gun quickly runs out of charge which better reinforces that both tools are for defensive use, not offensive. Baton is still useful for tripping and disarming for those robust enough to target limbs with it, and its description has been updated to make its capabilities more intuitive to those who inspect it.
> 
> It also helps bring the Captain and HoS starting power level down to a more reasonable level without forbidding them from access to their literal starting equipment and it gives antagonists a new avenue to acquire some basic and concealable weaponry, and while it has limited uses, they won't have to find a sneaky way to charge or reload."

## Testing Photographs

<details>
<summary>Screenshots</summary>

image

image

</details>

## PR References
- https://github.com/BeeStation/BeeStation-Hornet/pull/6754

## Changelog
:cl: DoctorSquishy, Buggy123, St0rmC4st3r, Rukofamicom
add: Adds PTSD - a slightly modified version of the miniature energy gun with 3 fewer disabler shots per charge, but the ability to fully recharge itself in 120 seconds.
balance: All heads of staff have a PTSD in their bag.
balance: The HoS and Captain no longer have roundstart access to a full size energy gun due to acquiring PTSD. They do still have their unique weapons.
balance: To make up for the increased firepower, the telescopic baton is no longer deals stamina damage, except when targeting arms. It is still effective for tripping and disarming, but not locking someone down in place indefinitely.
/:cl:

### CODE REVIEW

**Review by nednaZ — CHANGES_REQUESTED** [review]
Seems decently balanced, I think reducing the number of lethal shots by one or two may be good though.

I'd like the mini e-gun removed from the HoP locker and the full e-gun removed from the captain's locker so we aren't overarming them.

**Comment by DoctorSquishy** [comment]
> Seems decently balanced, I think reducing the number of lethal shots by one or two may be good though.
> 
> I'd like the mini e-gun removed from the HoP locker and the full e-gun removed from the captain's locker so we aren't overarming them.

Oh yeah I forgot about the guns in their lockers, I'll make the changes.

**Comment by nednaZ** [comment]
Running a test merge as there will be few changes from here

**Comment by DoctorSquishy** [comment]
> Running a test merge as there will be few changes from here

No problem, I am willing to change some things to improve its balance.

**Comment by nednaZ** [comment]
After doing some tests and seeing them used, I think the only change I'd make is to lower the capacity by 2 (2 disabler, 1 lethal).
Right now it's enough to throw someone into hardcrit if you hit every shot, but I want this to be a deterrent rather than an ideal weapon.

Baton changes are looking good for now

**Comment by DoctorSquishy** [comment]
> After doing some tests and seeing them used, I think the only change I'd make is to lower the capacity by 2 (2 disabler, 1 lethal). Right now it's enough to throw someone into hardcrit if you hit every shot, but I want this to be a deterrent rather than an ideal weapon.
> 
> Baton changes are looking good for now

Adjustments done

**Review by nednaZ — APPROVED** [review]
Seems like a good change overall

**Pull request merged**
