### PR TITLE
Bluespace Silo Changes

### PR DESCRIPTION
**Pull request by nednaZ**
# About The Pull Request

Removes the remote_materials component entirely.

Replaces all usage of ore silo connection with a local storage.

Changes the base cost of fabricators to be 100% (up from 160%)

Removes the Silo RCD Upgrade and related research.

Adds Kitchen and Mail accesses to the lowpop access list.

Removes all references to silo logging.

## Why It's Good For The Game

The ability to magically pull resources out of any lathe at any time makes it possible for one person to drain the entire station at once, without even having to loot the vault.

This requires crew to actively go to Cargo and retrieve materials, increasing player foot traffic and interactions between departments.
Adds risk to deliveries, making a cargo tech with haul gloves a good idea to secure your items.

Doing this is the first step to making the economy more player based rather than an invisible department giving you materials.

## Changelog

:cl:
balance: Changes the base cost of fabricators to be 100% (up from 160%)
balance: Doubles the storage capabilities of fabricators
del: Removes the ore silo's remote capabilities
del: Removes the Silo RCD Upgrade and related research.
add: Adds Kitchen and Mail accesses to the lowpop access list.
add: Cargo techs start with H.A.U.L. gloves
/:cl:

### CODE REVIEW

**Comment by wraith-54321** [comment]
it might be good if engie could still have some way to take resources, when sealing a hull breach I dont really have time to walk down to cargo and hope they give me stuff.

**Comment by Xkeeper0** [comment]
I do not have words for how awful of a change this is.

If I wanted to play Goon, I'd go play Goon. The ore silo, and the ability to distribute materials to the entire station as a miner, is (was?) one of the defining things I list when I talk about the benefits of playing non-Goon codebases, and this just deleted it.

**Comment by KonKonBreezeFox** [comment]
this just makes stuff more bothersome

**Comment by nednaZ** [comment]
Closing due to player poll.
Taking the ideas from playtests and feedback to create future QOL changes.

**Pull request closed without merging**
