### PR TITLE
Adds Streamer RNG to the game

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
at the request of ook adds streamer rng to the game to make content more interesting, will read from a json of ckeys and at a chance decided by admins and game modes will weight antags towards streamers

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
/:cl:

### CODE REVIEW

**Comment by Blueturbo47** [comment]
Could this be changed to a like set rank thing? Could be abused for people who just stream a few times, but play a lot offline too, since you should be ahelping when streaming, and admin can add you to the rank for a day or whatever.

**Comment by lmenvs** [comment]
> Could this be changed to a like set rank thing? Could be abused for people who just stream a few times, but play a lot offline too, since you should be ahelping when streaming, and admin can add you to the rank for a day or whatever.

We will probably have a pretty heavy vetting process to who gets added to the list.

**Comment by wraith-54321** [comment]
Next is totally stream integration

**Comment by wraith-54321** [comment]
Also a 50% rate is too high, with an antag rate that high you will run out of stuff to do as antag, also with the way it works right now its going to make it near impossible to roll antag as a non streamer.

**Comment by lmenvs** [comment]
> Also a 50% rate is too high, with an antag rate that high you will run out of stuff to do as antag, also with the way it works right now its going to make it near impossible to roll antag as a non streamer.

Agree, should be like 20% at most.

it might be a better option to give streamers antag tokens and automate that, or have an admin verb that lets them choose someone to cut in line before the round starts.  that way it still seems somewhat organic

**Comment by wraith-54321** [comment]
I know yog has an auto token redeeming system, so we could look at that.

**Comment by dwasint** [comment]
> Also a 50% rate is too high, with an antag rate that high you will run out of stuff to do as antag, also with the way it works right now its going to make it near impossible to roll antag as a non streamer.
.
this was the number ook wanted for now we can change it later

**Comment by dwasint** [comment]
> I know yog has an auto token redeeming system, so we could look at that.

its not automatic its semi auto as they still need to be approved

**Comment by wraith-54321** [comment]
One possible way to do auto token redeems(and other things) would be have an admin bot on that can run commands on a provided Ckey. For tokens this would be giving someone the antag datum in their TP.

**Comment by lmenvs** [comment]
> One possible way to do auto token redeems(and other things) would be have an admin bot on that can run commands on a provided Ckey. For tokens this would be giving someone the antag datum in their TP.

I would much rather we use Goons system that just means antag token = you cut in line in the antag rolls. Less hassle for admins

**Pull request closed without merging**
