### PR TITLE
Smooth out dizzy animation

### PR DESCRIPTION
**Pull request by lmenvs**
## About The Pull Request
see title

## Why It's Good For The Game
makes it less awful to look at.  Still pretty nauseating but that's kinda the point

## Testing Photographs and Procedure

<details>

<summary>Screenshots&Videos</summary>

Put screenshots and Videos documenting testing and execution of intended behaviors here

</details>

## Changelog
:cl:
fix: fixed dizzy animation
/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
Just gave it a test and there was seemingly no change on how jerky the animation is.

**Comment by lmenvs** [comment]
> animation

How did you test so I can see if it's based on computer performance

**Comment by Gboster-0** [comment]
Quick question, why does this remove
#include "code\modules\pool\components\swimming_felinid.dm" and
#include "code\modules\mob\living\carbon\human\species_types\felinid.dm"?

**Review by Merlin1230 — APPROVED** [review]
I remember this being MUCH nicer then the current one, a lot smoother for me.

**Pull request merged**
