### PR TITLE
Changed view screen to 21x15

### PR DESCRIPTION
**Pull request by Merlin1230**
## About The Pull Request
changes the game screen size to 21x15

TODO:

- [x] actually test this
- [ ] make hearing and stuff like that works
- [x] make sure splash screens fit

## Why It's Good For The Game
W I D E

### CODE REVIEW

**Comment by nednaZ** [comment]
Would like a "before and after" style picture, so we can get an idea of how it will look and feel

**Comment by Merlin1230** [comment]
> Would like a "before and after" style picture, so we can get an idea of how it will look and feel

I haven't actually tested if this works yet, when I do I'll make some

**Comment by Kapu1178** [comment]
This alone does not work. We have refined alot of systems to work with our viewport size.

**Comment by Merlin1230** [comment]
Yeah I assumed so, but I'll go through and find those hardcoded definitions

**Comment by nednaZ** [comment]
Closing due to inactivity.

**Pull request closed without merging**
