### PR TITLE
Ports Mod-Pc and other changes needed for PDA -> Tablet conversion [UPSTREAM PORT]

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
https://github.com/BeeStation/BeeStation-Hornet/pull/7551
https://github.com/BeeStation/BeeStation-Hornet/pull/7338
https://github.com/BeeStation/BeeStation-Hornet/pull/7351
https://github.com/BeeStation/BeeStation-Hornet/pull/7112

## Why It's Good For The Game
better mod tablets are cool and needed because they will soon be everywhere

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
refactor: Software Downloader program UI revamp
tweak: The NtOS home screen has been updated with disk and ID eject buttons.
add: Added support for modular PC expansion bays, or hardware bays designed to be used by nonessential hardware. Devices have a limited number of bays (tablets less than others).
balance: The AI card slot, printer, and APC-siphoning recharger are now expansion bay hardware.
balance: The modular PC atmos scanner now requires a new expansion bay hardware item - the sensor package. Certain shift-start tablets have been adjusted to reflect this.
refactor: Modular PC card readers have been split -- The primary ID card reader, which comes pre-installed on nearly all devices, and a secondary ID card reader which is an expansion bay hardware and will need to be purchased separately. Certain shift-start devices have a secondary reader pre-installed.
fix: Buying a tablet from the Laptop/Tablet vendor, and paying extra for the mini-printer, will now attach the correct printer rather than attempt to stuff a laptop printer into a tablet and silently fail but still take your cash.
add: Added icons for all modular computer programs
add: Supermatter Monitoring will now send notifications if the app is closed with a supermatter selected, and the selected supermatter starts delaminating.
fix: Modular computers can now be attacked with non-help intent.
code: Fixes a runtime error with recharger examine text if the inserted item's power cell is null
fix: Fixed a runtime with ID modification program when the second ID slot is missing.
fix: ID modification program now follows the standard for ID reading and requires you to insert your card.
tweak: Primary and secondary ID card slots in ModPCs have separate names to make it easier to differentiate.
tweak: Borgs and AIs now start with their borgHUDs/siliconHUDs on by default.
add: Added tablets to cyborgs. Humans can install apps to it by using portable data disks from the Deluxe Silicate Selections vendor and inserting the data disk with programs uploaded to cyborgs.
add: Added a borg self-management app to integrated cyborg tablet.
del: Removed most Robot Commands verbs in favor of the app.
tweak: Some lesser-used elements on the cyborg HUD are now in the management app.
add: Cyborgs can now change their headlamp color using the integrated tablet flashlight
add: Hud is now tracked based on your card appearance. HoP is now supposed to repaint crews' card in order to give them correct hud icons, or securities(+ghosts) will blame you.
add: every card now has default hud icons. (i.e. Captain's Spare card has a blank command HUD, budget cards have blank department color HUD)
add: added more PDA style options to PDA painter. (deputy, prisoner, heads, unassigned, etc)
refactor: PDA painter is now easy to recognise colourising style easier.
tweak: Some job HUDs are now only available through emaged ID card repainter.
tweak: crew monitor now tracks crew job color based on hud state.
tweak: Assistant id card crew objective is now greentextable when your card is painted even if the job name is still assistant.
add: hud image based defines
refactor: crew manifest is based on hud state.
refactor: PDA painter machine now updates the crew manifest upon ID repainting
refactor: changes to chameleon code and agent card, to make Hud icon update working. Chameleon agent card has earned QoL. They'll get a default job name of a card type you chose once changed.
add: agent card will be randomised upon EMP. (random hud icon, random job name, random icon)
add: broken chameleon agent card (with all wiped access, and unable to copy accesses from another card)
add: broken chameleon kit will have broken chameleon agent card.
add: new hud icons, new card images (blank symbol department color hud icons, new hudking icon)
del: 9x9 pixel size 'hudking' hud icon
add: New card types for the purpose of chameleon agent card. (i.e. "their majesty's gold identification card")
tweak: Some card types are now blacklisted from chameleon agent card - because they don't make sense. (i.e changeling fake ones)
tweak: your card paycheck department is now re-assigned based on your hud icon state. if your hud icon is red with job name 'not real security', you are paid by the security budget. the process happens when you repaint a card or give a new job name to a card.
tweak: not all gimmicks are in civilian department anymore. Psychiatrist is medical, and Stage Magician is service like their mime/clown fellows. (VIP and barber are still service)
tweak: The title bar of Modular PC programs now contains the program's name instead of the file name.
fix: Fixed a bunch of modular PC runtimes with try_eject.
tweak: Anyone can now download BotKeeper (tablet app). Only bots your current ID can unlock will be listed to control.
fix: Fixed NTOS File Manager renaming/deleting wrong programs when used with external disk.
code: Improved ID console name/job sanitization code, and added feedback for when sanitization fails.
fix: Modular ID console will no longer insert/eject ID card for AI or to telekinesis players.
qol: Supermatter Monitor now shows total moles. It glows red if your SM is going to singloose.
code: Supermatter's defines have been moved into it's own file in the __DEFINES folder.
add: Modular Computers equipped with the new integrated radio card chip can now be used as a remote signaller.
add: Scientists now start with tablets pre-equipped with a signaller chip and the program downloaded.
fix: Fixed a bug preventing the Job Management app from de-prioritising jobs when 5 or more jobs were prioritised.
code: Improved computer hardware code and delete management.
qol: The Atmospheric Scanner tablet program will show the tile's temperature as both degrees C and K.
qol: Modular Devices now have auditory feedback for disassembly, and use balloon alerts for various errors.
fix: Signaller code transmissions on the 145.7 frequency are no longer received by all signallers, even if they are tuned to another frequency.
fix: Fixes tablet not updating appearance immediately after it is repaired.
refactor: Modernized NTChat, now with muting and pinging!
admin: NTChat now has a filter check.
qol: Observers can now see NTRC messages if they have PDA messages enabled.
fix: Brig physician slots can no longer be increased through the Job Management tablet app.
tweak: The Software Downloader will now say "Insert ID" instead of "No Access" if no ID is inserted, and no longer responds to hovering the button.
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
you will like the changelog, robust everything you want

**Comment by EvilDragonfiend** [comment]
You need more ports from mine.
* https://github.com/BeeStation/BeeStation-Hornet/pull/7246
* https://github.com/BeeStation/BeeStation-Hornet/pull/7250
* https://github.com/BeeStation/BeeStation-Hornet/pull/7253
* https://github.com/BeeStation/BeeStation-Hornet/pull/7254
* https://github.com/BeeStation/BeeStation-Hornet/pull/7279
* https://github.com/BeeStation/BeeStation-Hornet/pull/7296
* https://github.com/BeeStation/BeeStation-Hornet/pull/7328
* https://github.com/BeeStation/BeeStation-Hornet/pull/7381

It had some buggy since I touched it, but I think there is no bug anymore.
I think cherrypicking some codes from current bee would work faster since checking all PRs will be complex due to bug fixes

**Comment by itsmeow** [comment]
You will probably also want these PRs:
- https://github.com/BeeStation/BeeStation-Hornet/pull/7620
- https://github.com/BeeStation/BeeStation-Hornet/pull/7622
- https://github.com/BeeStation/BeeStation-Hornet/pull/7623
- https://github.com/BeeStation/BeeStation-Hornet/pull/7688
- https://github.com/BeeStation/BeeStation-Hornet/pull/7797

**Comment by itsmeow** [comment]
> Maybe pda auto update part might be unnecessary (but ghost role spawn setting is good) I am not sure.

Yes, if they intend on porting tablet PDAs, none of your original code is there anymore (RIP)

**Comment by itsmeow** [comment]
Also you forgot to mention that this ports the HoP console PR

**Comment by nednaZ** [comment]
Before I even review it, I want a better reason on why this is even a good change.
This is a massive PR for something that has no real documentation and a wall of entirely disconnected changelogs.

**Comment by dwasint** [comment]
Gonna close for now as this is a massive amount of changes and this is only like part 1 of 3 need to create a design doc and get approval on it before i re-open

**Pull request closed without merging**
