### PR TITLE
Vent Clog event sucks so it's gone.

### PR DESCRIPTION
**Pull request by Zembaflemba**

### CODE REVIEW

**Comment by dwasint** [comment]
Vent clog straight up lasts for like 4 minutes its tame as can be as everything evaporates

**Comment by Zembaflemba** [comment]
Except when you get acid and it melts everything in the room. That shit ruins rounds.

**Comment by nednaZ** [comment]
Non-branched PR, removes extra events out of scope and it has no changelog or information in the PR header.
I'm willing to consider nerfs and chem blacklists for the event, but not a hard removal.

**Comment by Zembaflemba** [comment]
Just mirror the one from Bee, they removed it in april.

**Comment by dwasint** [comment]
for different reasons, vent clog before liquids was one of the single biggest causes of lag out there. Just remove acids from the vent clogs if thats your gripe

**Comment by nednaZ** [comment]
Blacklisting certain chems from it would be perfectly fine.

**Pull request closed without merging**
