### PR TITLE
MORE LOBBY MUSIC FOR MONKESTATION

### PR DESCRIPTION
**Pull request by WonderPsycho**
# About The Pull Request

ADDS MORE LOBBY MUSIC TO MONKE SS13 SERVER

## Why It's Good For The Game

more lobby music, more variety, and more music to listen to and chill out to while players wait for the round to start

Listed added Lobby music
Bomberman Hero - Redial
PilotRedSun - bund6
MashedByMachines - THUNDERDOME/Sector 11
Onulle - CLOWNMAN REDIAL
g0urra - Mashup Forward
Mighty Switch Force 2 - Got2BAStar
Admiral Hippie/Space Hippie/Lawligagger - Clown.wmv and Space_Station_13.mp4 (two ss13 classics)
Jeroen Tel - Tin Tin on the Moon (C64 Version) 
X-CEED - Title1/Flip Flap

### CODE REVIEW

**Comment by WonderPsycho** [comment]
uhhh i need help on removing the old Look Forward Part of it the PR, i already added Look Forward by Skyline into the lobby music for Monke

**Comment by WonderPsycho** [comment]
wait nvm

**Comment by nednaZ** [comment]
One tip for the future, don't push your "Master" branch as a PR.
Use separate branches for every single PR you make.

**Comment by WonderPsycho** [comment]
> One tip for the future, don't push your "Master" branch as a PR. Use separate branches for every single PR you make.

aight should do that next time to make things more easier andnot give out stuff i already had a PR for Monkestation and stuff

**Comment by WonderPsycho** [comment]
will note that after this PR, i am gonna work on and finish up the spiderling vomiting/spiderling infestation symptom for monke virology in new PR and also work on some new random rooms for monke code for another PR so yeah

**Comment by WonderPsycho** [comment]
will say, (since i kind of did not mention before) that this PR is all set and ready and i have no other stuff I want add or need to fix, for anyone this PR is ready to be reviewed and stuff, awaiting people to review it and such

**Comment by nednaZ** [comment]
It's being reviewed.

But with how much music there is, we won't likely be able to merge it.
There are a lot of risks putting in raw music that could potentially cause stream issues.

You also still haven't put in actual license info or proof of permission into this PR at all.

**Comment by nednaZ** [comment]
After internal talk, we're closing this because any new music just increases the risk of Twitch automatic shutdown.

**Pull request closed without merging**
