### PR TITLE
fixed vending machine issues

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Oops forgot to correctly apply job discounts to the ui, no idea what was going on with the cash getting given, fixed though as i removed discounts and you just get it for free like before

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
fixes:vending machines NaN and it giving credits
/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
Will test merge

**Comment by nednaZ** [comment]
Not working as intended.
Everything that costs money now says FREE, but charges.

**Comment by nednaZ** [comment]
Rework the original PR with this as well as any fixes required

**Comment by dwasint** [comment]
> Not working as intended. Everything that costs money now says FREE, but charges.

can you give any examples of this it was not working like that on local at all

**Pull request closed without merging**
