### PR TITLE
Wizard content pack 2(the big one)

### PR DESCRIPTION
**Pull request by wraith-54321**
# About The Pull Request

Adds a new spell, Space time portal.
When cast summons a mob spawner with timed life.

Adds a new artifact, Reactive Talisman.
Its reactive armor that when the wearer gets hit the owner casts a spell.

Event fast mode.
Makes an event happen every 10 or so seconds x times.

Buffs the cost of Summon Apes from 3 to 2.
Until monkey AI gets fixed the only real threat from the spell is the gorillas, which can be run away from.

Buffs the Battlemage Armor charge to give 12 hits instead of 8.
I never see anyone use the battlemage armor, let alone the charges.

Reworks Mjollnir to now instead be a spell, the spell has a 65 second cooldown and Mjollnir gets qdeled 25 seconds after summoning, mjollnir now deals stam damage on hit instead of an instant 6 second stun. The first time Mjollnir is thrown each summon it will "bounce around the room" and then return to you.

Fixes living statues to be able to use their spells.

Reworks the spell Disintegrate into the spell Smite, a 2 range pointed spell with a 30 second cooldown that when used will pick a (mostly)random admin smite to apply to the unluckly target.

Buffs the cost of Barnyard Curse from 2 to 1.

Nerfs the cost of the wand belt from 2 to 3.

Reworks mindswap to be an AOE spell that randomly swaps the minds of everyone in a area, whoever gets put into the wizard's original body gets turned into an imposter wizard. This one is gonna need some testing as I can only kind of get 2 bodies to test with.

Restores multifire to aimed spells and tracking to spell cards, spell cards have had their damage reduced to 1 however now pierce everything, that means **you.**

Buffs the cost of Bind Soul from 3 to 2.

Buffs the cost of Locker Staff from 2 to 1.

Buffs Soultap to not require robes.

Nerfs the cooldown of mutate from 40 to 60 seconds.

Buffs the cooldown of Smoke from 12 to 6 seconds.

[PORT] The Cursed Duffel Bag spell from https://github.com/tgstation/tgstation/pull/55286

Adds a wizard event and artifact that create fake antags, fake antags are pacifist versions of antags that sometimes get gimmick versions of their objectives, fake nukie has to detonate beer nuke, ETC. The artifact is a weapon that turns dead bodies with souls into fake antags.

Adds 3 new wizard events: Gifts for everyone, clown storm, and greater summon apes.
Greater summon apes: Portal storm with angry monkeys and gorillas, most of the monkeys have weapons. Oh no.
Clown storm: Portal storm with clown mobs.
Gifts for everyone: Gives all sentient carbon mobs an anything gift.

The big one, WIZARD WAR.
The wizard den now spawns with a new item to cast a power ritual(declare war), when used the station will be alerted and teleport scrolls will not work for 20 minutes also has to be used in the first 5 minutes like nukies.
Doing the ritual will give you: 3 Gem Encrusted Hardsuits, 3 Power Charges that increase a spellbook's uses by one, and 2 reinforcement scrolls that summon 2 lesser wizards, these wizards have 5 points instead of 10. The station will also get 10k credits.
The objective: when declared 8 vortex rifts will spawn around the station, 4 of these must be stabilized(4 second interact 8 times)
doing this will summon a magical vortex to the station, forcing a 5 minute shuttle, summoning a bunch of ghost wizard, giving all current wizards +10 points, and casting summon guns/magic.

[X] New artifacts
[X] New spells
[X] Get all war features working
[ ] Balancing
[ ] Bugfixes 
[ ] Testing
[ ] Add logging(gonna need an admin to tell me where I should put it)

## Why It's Good For The Game

More content and balance good, hopefully.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: A new spell, Space Time Portal
add: A new wizard artifact, Reactive Talisman
add: Ports the Duffel Bag Curse spell from https://github.com/tgstation/tgstation/pull/55286
add: A wizard artifact and event that create fake antagonists
add: An ape and clown themed portal storm wizard event.
add: A summon gifts wizard event
add: WIZARD WAR
tweak: Mjollnir has been reworked into a spell
tweak: Disintegrate has been replaced with Smite
balance: Buffed Battlemage Armor charges from 8 to 12
balance: Buffed Lesser Summon Apes cost from 3 to 2
balance: Buffed cost of Barnyard Curse from 2 to 1
balance: Buffed cost of Bind Soul from 3 to 2
balance: Buffed cost of Locker Staff from 2 to 1
balance: Buffed Soultap to no longer require robes
balance: Buffed the cooldown of Smoke from 12 to 6 seconds
balance: Nerfed the cost of the wand belt from 2 to 3
balance: Nerfed the cooldown of Mutate from 40 to 60 seconds
fix: Living Statues can now use their spells
fix: Aimed spells can now correctly multifire
fix: Spell cards have had their tracking restored
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
> reinforcement scrolls that summon 2 lesser wizards, these wizards have 5 points instead of 10.

I think you under-estimate how bullshit strong one, nevermind **three** wizards are

**Comment by wraith-54321** [comment]
> I think you under-estimate how bullshit strong one, nevermind **three** wizards are

The lesser wizards only get 1 extra point value then an apprentice and they get to choose what they get, although I could make it so they cant buy any of the summoning items. Also cargo now gets 10k extra credits as well.

**Comment by Zonespace27** [comment]
> > I think you under-estimate how bullshit strong one, nevermind **three** wizards are
> 
> The lesser wizards only get 1 extra point value then an apprentice and they get to choose what they get, although I could make it so they cant buy any of the summoning items. Also cargo now gets 10k extra credits as well.

5 points (on top of the 3 scrolls for 1 spell point each, which effectively takes you up to 6) is more than enough to get, say, mjolnir, recall, and teleport, before wiping out the station with your other two wizard buddies

I get the idea here (warops but wizard), but wizards operate on such a fundamentally different power scale that this is far closer to "wait 20 minutes, then wipe the station in 10" than actual warops.

**Comment by wraith-54321** [comment]
> 5 points (on top of the 3 scrolls for 1 spell point each, which effectively takes you up to 6) is more than enough to get, say, mjolnir, recall, and teleport, before wiping out the station with your other two wizard buddies

Honestly this makes me realize I should nerf mjolnir because it's THE meta, literally the only reason to not take it is due to getting it stolen, but recall nullifies that.

**Comment by Supermichael777** [comment]
Frankly that's because almost all the actually usable spells are just different brands of the same boring murder.

You don't have wacky shit like suddenly leaving a trail of grease behind you, and many of the utility spells are way to predictable and/or crusty to control.   

For example, mindswap, in its current state, is a useless DBZ reference because it stuns both people for a long time.  It hearkens back to when a wizard had a station of 20 people to fight and could sometimes run into a lone secoff and get tazed. leaving the secoff in the cuffs and you running with gear.  Now whenever a wizard is about you have to fight the valid mob and the moment you try objectively one of the most chaotic non lethal spells your going to get ganked instantly.

What it needs is a bit of modern spice, like an abductor style objective for the person you swap telling them that no THEY ARE THE WIZARD, click to target instead of an old menu, or to stun everyone in LOS and mute the old body for a while so no one knows who the wizard is for a moment.

**Comment by wraith-54321** [comment]
Once im done working on Mjollnir and Smite I will do some of those things, I was also thinking maybe make the spell sleep everyone in an area so now you have no idea who the wizard could be. Or if I wanted to make it really interesting I could make it a randomly targeted AOE spell that swaps the mind of EVERYONE in the area.

**Comment by wraith-54321** [comment]
TG has grand ritual which should act as an effective replacement to wizard war once the rebase is done.

**Comment by wraith-54321** [comment]
Just gonna port this to the rebase

**Pull request closed without merging**
