### PR TITLE
Violent shotgun sound changes. For fun.

### PR DESCRIPTION
**Pull request by Sentient3780**
# About The Pull Request
I personally felt as if the noises that the shotgun makes were quite weak. I replaced them with sound files ripped from Halo 3. The Duke himself butted in after I showcased the changed sound files in a small video, and I was encouraged to put the changes into a PR and send it off. This is my first time making a branch and PR, and the sound files themselves are likely not up to standard. As a result, I heavily doubt that this will be merged at all.

But, this is still going to get out there, and into the public eye. Who knows what will happen next. :trollface:

## Why It's Good For The Game
No changes mechanically, aside from giving the user a <i>sliiiightly</i> better dopamine release upon using a shotgun.

## Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

https://cdn.discordapp.com/attachments/730199515826749512/1003075780164726814/8mb.video-RN1-rl8q7Q0P.mp4
https://medal.tv/games/byond/clips/uBD9ukGHgdegV/d13378onrK85?invite=cr-MSxHRlgsNDIwNTEyMjIs
https://www.youtube.com/watch?v=Cni-sM5zvuo

</details>

## Changelog

:cl:
soundadd: newer shotgun sounds ripped from Halo 3 are set in place
sounddel: old sound files for the shotgun are gone as a result
/:cl:

### CODE REVIEW

**Comment by Serxule** [comment]
the discord link dont work

**Comment by Oricana-16** [comment]
discord link works, just download it

**Comment by Sentient3780** [comment]
Try this. I moved the video clip over to Medal and posted it there.
https://medal.tv/games/byond/clips/uBD9ukGHgdegV/d13378onrK85?invite=cr-MSxHRlgsNDIwNTEyMjIs

**Comment by Serxule** [comment]
neither are working for me still, could just upload it to youtube

**Comment by Sentient3780** [comment]
I got it uploaded to Youtube, as an unlisted video.

https://www.youtube.com/watch?v=Cni-sM5zvuo

**Pull request merged**
