### PR TITLE
Ports various sprites while i wait for wallening

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Sprites from eris
  Emitters
  Field Generators
  Slimes
  Extracts
  Body Bags
  Beakers
  Roller Beds
  Packages
  Disposals
  Gibber
  Processor
  Cleaver
  Fork
  Rolling Pin
Sprites from Yog
 Canisters
Sprites from Tau Ceti
 Heaters
 Portable Pumps
 Portable Siphons
 Suit Storage
 Rad Collector

## Why It's Good For The Game
Since i plan on porting to wallening in the future updating our sprite sets to a 3/4 base is a good thing

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

image

image
ignore crate i decided against those for now

image

image

image

image

image

image

image

image

image

image

</details>

## Changelog

:cl:
changes:some sprites
/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
The sprites look pretty good. However I think I may take this one to a vote, simply because it does change a lot of the existing art

**Comment by retlaw34** [comment]
The classic suit storage resprite is not from eris, I made it. The industrial suit storage unit is from eris.

You should probably credit who made the sprites or list where you got them from, either by linking to the codebase or PR that added them.

Rad collecter appear to be from TG and Canisters are definitely from Yogstation

**Comment by dwasint** [comment]
drafting until i get links to all the prs that added these

**Comment by wraith-54321** [comment]
I like all the sprites besides the crate and engie secure storage machines

**Pull request closed without merging**
