### PR TITLE
[TM FIRST] HoleStation - The Dedicated Deadpop Map

### PR DESCRIPTION
**Pull request by unit0016**
# About The Pull Request
Ports over Holestation from my personal repository in all it's glory, adjusted for Beecode (And Monke, by extension). Hole's gimmick is being tailored made for the lowest of lowpop, with rounds of only 5 players playing smoothly - if quickly - on it through testing.

A lot of jobs have been scaled back or outright removed compared to other station maps, but every important item and job remains, with some adjustments for these tailored conditions (One roundstart BORIS module, for instance.)

It's votable, and can be picked there's under 15 players.

To do:

- [x] Piping
- [x] Cameras
- [x] Restrict jobs that aren't accounted for
- [x] ACCESS.
- [x] Emergency Shuttle
- [x] SOMEHOW Fix the arrivals shuttle not loading
- [x] Get #353 merged

## Why It's Good For The Game
When deadpop hits, it's nice to have a map tailored for it. Holestation is about the size of two departments on any other map in it's entirety.

## Testing Photographs and Procedure

<details>
<summary>Screenshots</summary>

# THESE ARE OUT OF DATE
Top Floor:

Bottom Floor:

Emergency Shuttle:

Exploration Shuttle:

</details>

## Changelog

:cl:
add: A new deadpop oriented map has been added, Holestation!
server: Maps config has been tweaked for Holestation's existence, and will need to be updated.
/:cl:

### CODE REVIEW

**Comment by unit0016** [comment]
Until the Issue with arrivals is sorted out this PR is staying on draft. No arrivals shuttle means no worky game

**Comment by williamcll** [comment]
Isn't Multi-Z broken on beecode right now? Especially power delievery.

**Comment by unit0016** [comment]
> Isn't Multi-Z broken on beecode right now? Especially power delievery.

Everything besides power is working. Power works perfectly fine on the lower floor but I'm gonna need to find some way to work around it at the moment. maybe the smart wires multi-z cable hub'll be of help...

**Comment by unit0016** [comment]
Got a way to make this work, Put a TEG upstairs. If multi-z pipes work the cable relay being busted won't matter

**Comment by unit0016** [comment]
Okay, I need to TURBO rework the engine, as-is it's primed for delamination. Fucking hell why can't shit just work

**Comment by unit0016** [comment]
We good again

**Comment by nednaZ** [comment]
Security has 0 spawns (excluding Detective)
Armoury is one thermite away from the hallway.

The aux base location makes me laugh, since it's implied that you drop the base.
Would fall right onto medbay, not actually an issue though.

Top right pipe of the cooling loop could be sabotaged by someone putting a pipe on a wall in maint.

Hydroponics is missing a gene extractor.

**Comment by unit0016** [comment]
> Security has 0 spawns (excluding Detective) Armoury is one thermite away from the hallway.
image
Fixed this and the gene extractor, taking a look at the cooling loop to see what can be done to make it more robust

**Comment by DoctorSquishy** [comment]
SM Area got renamed so be sure to update it to the Engine_Core Area. You can var edit the name to Supermatter Core if you like

**Comment by williamcll** [comment]
image
distro thermomachine in atmos should be either off or set to heating at room temperature.
image
Where are the atmos computers? 
image
HFR? this isn't /tg/
image
What's the reasoning behind having SM engine room scrubbers connected to SM waste rather than waste distro?

**Comment by unit0016** [comment]
> Best to put railings in upper maints 

Railings are broken on beecode and only allow you to mount them in a specific direction. Plus falling is funny and taking that out would remove the soul

> What's the reasoning behind having SM engine room scrubbers connected to SM waste rather than waste distro?

It makes more sense if you zoom out to the rest of the network:
image

**Comment by williamcll** [comment]
SM emitters can fire straight into cargo if SM blows

**Comment by Killermankey** [comment]
I'd just like to say as a idiot engie that while having a sm powered TEG is cool... I have met at least 10 other engineers that have no idea how to make it work and usually delam it. Is there any way you can have a piece of paper for instruction in engineering? If its meant to be deadpop then there should be instructions so non engies can do it.

**Pull request merged**
