### PR TITLE
New metal chair sprite

### PR DESCRIPTION
**Pull request by png103**
# About The Pull Request

## Why It's Good For The Game

The current chair sprite has been unchanged since the original goonstation code release and is inconsistent with the rest of the chair sprites
## Testing Photographs and Procedure

Before
image
After
image

</details>

## Changelog

:cl:
tweak: changed the metal chair icon to be more consistent with the rest
/:cl:

### CODE REVIEW

**Comment by WonderPsycho** [comment]
i don't know who you are, but nice chair resprite

**Comment by nednaZ** [comment]
So two things.

1: Did you create this sprite yourself?
2: Please modularize the change by putting the new sprites in the MonkeStation directory, then modify the chair code to point towards that .dmi

**Comment by Merlin1230** [comment]
> i don't know who you are, but nice goon chair resprite PR

Those aren't the goon chairs. similar style however.

**Comment by png103** [comment]
> So two things.
> 
> 1: Did you create this sprite yourself? 2: Please modularize the change by putting the new sprites in the MonkeStation directory, then modify the chair code to point towards that .dmi

actually now that i think about it i'm not sure where the sprites originate from, i've just seen a bunch of servers use them

**Comment by png103** [comment]
oh and so, what you're suggesting is that i create a separate dmi with the chair sprite instead of it replacing the current one?

**Comment by nednaZ** [comment]
Found the source of the sprites, looks like that part is all good.
Just need the modularization part done and I'm 100% in favor of new chair sprites!

If you need help with that, just ping me on the discord.

**Comment by nednaZ** [comment]
> oh and so, what you're suggesting is that i create a separate dmi with the chair sprite instead of it replacing the current one?

Yeah, separate .dmi in the Monkestation folder to prevent conflicts when we update from Bee main.
You just need to update the chair code at that point to point at the new icon file.

**Comment by WonderPsycho** [comment]
> > i don't know who you are, but nice goon chair resprite PR
> 
> Those aren't the goon chairs. similar style however.

oh didn't realize sorry

**Comment by nednaZ** [comment]
Inactive project.

**Pull request closed without merging**
