### PR TITLE
Neuromods + Evolved Mimics

### PR DESCRIPTION
**Pull request by Oricana-16**
# About The Pull Request

You will be able to surgery out mimic organs from their corpses. When you put a mimic organ through the E.X.P.E.R.I-mentor you'll get a random neuromod that gives you an ability. These will all need to be balance checked so none of these are 100% staying in.

Misc ToDo
None.

Sounds
- [ ] Phantom Shift
- [ ] Stalk
- [ ] Smuggle
- [ ] Scramble

Particles
- [x] Phantom Shift
- [ ] Stalk

Sprites
- [ ] Neuromod Injector
- [x] Phantom Shift Icon
- [x] Kinetic Blast Icon
- [x] Stalk Icon
- [x] Smuggle Icon
- [x] Scramble Icon
- [x] Mimic Composition
- [x] Electrostatic Burst
- [x] Psychoshock Icon
- [x] Mindjack
- [x] Biomatter Transfer
- [ ] Track
- [ ] Weapon Transformation

Neuromods
- [X] Phantom Shift - Teleport anywhere within 4 tiles
- [x] Kinetic Blast - Throw people away from you
- [X] Stalk - Hide in people's shadows. Releases on the shadow owner going into crit or dying.
- [x] Smuggle - Hide items inside of your body. Releases on death.
- [x] Scramble Electronics - EMP a nearby tile
- [x] Mimic Composition - Ventcrawl and walk through grilles for 30 seconds
- [x] Electrostatic Burst - Zap in a focused area
- [x] Clown - Clown
- [x] Psychoshock - Confuses and stuns a target for a bit
- [x] Mindjack - Temporary mind control/hypnosis with a relatively big cooldown
- [x] Biomatter Transfer - Heal someone at the cost of your own health.
- [x] Track - Mark a person as a target and know the direction they're in
- [x] Weapon Transformation - Transform an item into a weapon depending on its properties (sharp, blunt, etc.)
 
Mimics

Default Mimic - Deals 7 brute and 7 clone damage.
- [x] Greater Mimic - Can disguise as more/bigger things, 18 brute damage (as opposed to 14 total damage mimics normally do)
- [x] Voltaic Mimic - Deals 5 brute and 5 burn damage, stuns people on hit, can activate a 7 tile EMP on a 1 minute cooldown
- [x] Thermal Mimic - Deals 7 burn and 7 clone damage, is immune to fire, ignite targets on hit.
- [x] Shifty Mimic - Deals 5 brute and 5 clone damage, can teleport (30 sec cd), also bringing whoever they're latched onto with them.
- [x] Kinetic Mimic - Deals 12 brute damage, and has Kinetic Blast
- [x] Oracle Mimic - Deals 5 brute and 5 clone damage,  can ghost temporarily to look around.

I told Zan that i'd take a break from mimic stuff yesterday and I lasted a total of 5 minutes before immediately working on neuromods

## Why It's Good For The Game

I love Prey (2017)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Phantom Shift
https://cdn.discordapp.com/attachments/1014722731763310622/1014722987456475146/2022-08-31_18-42-09.mp4

Kinetic Blast
https://cdn.discordapp.com/attachments/1014722731763310622/1014722987901079624/2022-08-31_19-38-53.mp4

Stalk (I do hide under the target thing in this clip but that was removed cause not intended)
https://cdn.discordapp.com/attachments/1014722731763310622/1014722988450525275/2022-08-31_22-04-04.mp4

Smuggle
https://cdn.discordapp.com/attachments/1014722731763310622/1015043446332993667/2022-09-01_19-39-30.mp4

Electrostatic Burst
https://cdn.discordapp.com/attachments/1014722731763310622/1015622398835425331/2022-09-03_10-00-37.mp4

Shifty Mimic
https://user-images.githubusercontent.com/99915170/189491522-3c1c6a0a-de1a-4e3f-b9b5-927199b1dd4a.mp4

</details>

## Changelog

:cl:
add: Adds Neuromods. Surgery the organ out of a mimic and throw it in the E.X.P.E.R.I-mentor to discover a neuromod!
add: Adds evolved mimics. At the cost of half the replication cost, a mimic can ask the other mimics to allow them to evolve!
/:cl:

### CODE REVIEW

**Comment by Oricana-16** [comment]
Only the first 2 actually have corresponding neuromods in game, the rest are made up ones. If you have ideas for any, then post them here or in my dms.

**Comment by DoctorSquishy** [comment]
I too love Prey, now we just need the Gloo gun

**Comment by Oricana-16** [comment]
I'd love the floor gun but I have no idea of how you'd goo up the place that would be accurate enough to the game.

Clown gloo'ing sec would be super funny though.

**Comment by Oricana-16** [comment]
I'm going to limit myself on neuromods and mimic types for now, and only add the ones I already came up with. I'll add any others that I really want in another PR if I need to.

**Comment by Oricana-16** [comment]
I'll go over it all again tomorrow and do more testing, but I think it might be ready for a test merge

**Comment by Oricana-16** [comment]
After you review it and I make whatever changes, I want it to be test merged and then back to draft for a bit.
I hope to have the Baller mimic sprites before I completely finish this, but even if I don't I'd wanna make sprites for every neuromod

**Pull request closed without merging**
