### PR TITLE
Refactor icon smoothing to use 8-bit bitmasking [TM-FIRST]

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
This PR ports a number of tweaks from TG, mainly:
https://github.com/tgstation/tgstation/pull/52864
https://github.com/tgstation/tgstation/pull/53906
https://github.com/tgstation/tgstation/pull/54441
https://github.com/tgstation/tgstation/pull/54129

    bitflag list construct added: an associative list of bitflags for cheap and quick element comparison between two lists using the same system.

    canSmoothWith list turned into a bitflag list.

    smoothing_groups list added to substitute the type path list.

    smoothing procs turned into atom procs, refactored and optimized a bit.

    smooth directions redefined in order to fit in 8 bits for a future smoothing system

    some variable names changed, foreseeing a second smoothing system

    SMOOTH_OBJ flag added, for things that need to scan turfs for smoothing. The old locate() optimization has the risk of returning false negatives by finding a child and returning null while there might be one of the wanted type as well, as it doesn't match the type exactly.

    SMOOTH_TRUE and SMOOTH_MORE condensed into SMOOTH_CORNERS. The old behavior can be replicated using smoothing groups without loss.

    Does very minor code cleanup.

    Processing-wise didn't find a noticeable difference. The system loses on init a bit by setting the bitflag_lists, and by scanning whole turf contents for object smoothing (increasing accuracy), and gains by making less checks per target to smooth, through the same bitflag_lists.

    Memory-wise there should be a small improvement, given that on the old system we had 63512 canSmoothWith lists (a few typelists, most unique), and on this new system canSmoothWith + smoothing_groups are both bitflag_lists from the same pool, totaling 46 in number.

    Turn two typelists into string_lists, diminishing list duplication a bit.

This is a backend refactor on icon smoothing, using 8-bit bitmasking ( https://gamedevelopment.tutsplus.com/tutorials/how-to-use-tile-bitmasking-to-auto-tile-your-level-layouts--cms-25673 ).

This also allows for transparent object smoothing without the jank that was overlay smoothing.

## Why It's Good For The Game
This makes spriting much easier for us as we don't have to cut up sprites for overlays and instead can get the full picture at once, win for spriters. Rohesie made a tool to convert old sprites over to new ones incase anyone is needing help porting over to the new sprite types https://github.com/Rohesie/icon-cutter

## Changelog

:cl:
tweak: New table sprites from Sunset station (Credits to Quantum-M for the sprites)
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
This still has alot of modularization and removal of un-needed changes because i'm not gonna lie, i got desperate trying to find a fix and probably made way more file changes than needed

**Comment by nednaZ** [comment]
As a first request, can you make the changelog actually detail what this does?

**Comment by dwasint** [comment]
> As a first request, can you make the changelog actually detail what this does?

in terms of player facing changes this literally just adds the new sprite, should i put all backend changes in the changelog aswell?

**Comment by nednaZ** [comment]
Running a test merge.

**Comment by DoctorSquishy** [comment]
Fancy Table:

image

**Comment by dwasint** [comment]
> turbolift walls (Unused?)

they are unused

**Review by nednaZ — APPROVED** [review]
Test merges have ironed out the issues and it looks like it's stable enough to fully merge now.

**Pull request merged**
