### PR TITLE
Holestation Patch 2: Revengeance

### PR DESCRIPTION
**Pull request by unit0016**
# About The Pull Request
Adds the missing reflector vest and fixes a few stray exterior windows without shutters.

## Why It's Good For The Game
Isss Fix

## Changelog

:cl:
fix: Stealing the reflector vest is now possible on Holestation, and every external window now has a underlying window firelock.
/:cl:

### CODE REVIEW

**Comment by DoctorSquishy** [comment]
oh dear, I am gonna have to fix my test merge again

**Comment by unit0016** [comment]
> oh dear, I am gonna have to fix my test merge again

just run mapmerge2 it's fine

**Comment by unit0016** [comment]
'luv me mapmerge 2

**Review by nednaZ — APPROVED** [review]
Looks fine to me

**Pull request merged**
