### PR TITLE
Examine blocks

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
https://github.com/tgstation/tgstation/pull/67937
Adds Examine Blocks as seen on Skyrat and other servers, but tweaked a bit to look better

## Why It's Good For The Game
Helps multi-text outputs stand out from the rest of the chat, makes it way more readable when you use the various analyzers or examine someone or something

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

🆑 13spacemen, Gandalf2k15 ported by dwasint
add: Examining and other chat outputs now display in blocks to make them easier to see
fix: AI and borgs no longer have their name show twice upon being examined
/🆑

### CODE REVIEW

**Comment by dwasint** [comment]
this one is super simple gonna reopen

**Comment by warface1234455** [comment]
https://github.com/yogstation13/Yogstation/pull/15320/commits/a7c1c58195dd147788f9242bbb30899663db5e07

**Comment by dwasint** [comment]
addressed that now

**Review by nednaZ — APPROVED** [review]
Looks good to me

**Pull request merged**
