### PR TITLE
fixes pancake stacking

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
fix:pancakes stack properly again
/:cl:

### CODE REVIEW

**Comment by lmenvs** [comment]
Completely unrelated but is maple syrup a liquid

**Comment by dwasint** [comment]
> Completely unrelated but is maple syrup a liquid

No, currently not

**Comment by nednaZ** [comment]
Linters failed

**Review by nednaZ — APPROVED** [review]
Looks good to me

**Pull request merged**
