### PR TITLE
Subsystems are no longer allowed to sleep within fire() [UPSTREAM]

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Normally i would wait until this pr is merged, but with the big event tomorrow i want to try and stop the ss freezes that we have and this does that.

SSair.unpause_z was called by SSzclear, however it contained a CHECK_TICK. This introduced a CHECK_TICK into the master controller cycle, which would cause all subsystems to be frozen during high tick loads until that function could complete.

Check the parent pr for screenshots: https://github.com/beestation/beestation-hornet/pull/7274

This updates the function to instead command the air subsystem to unpause the z-level during its fire() call. It now also runs off the MC_TICK_CHECK instead. If it takes a super long time to run for whatever reason, rather than freezing the entire MC, only atmos will be paused for some time.

We also ignore space turfs for atmos reactivation, since it uses a static atmosphere anyway so shouldn't ever contain gas even if the ChangeTurf retains the initial atmos state.

Subsystem fire calls are no longer allowed to sleep at all. This should prevent this ever happening in the future.

## Why It's Good For The Game
No more TICK_CHECK within the master process call chain. This should fix all subsystems suddenly freezing up during high server load.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
fix: Timers, orbit updates and other subsystem related processes will no longer freeze when a z-level is unpaused from atmospherics.
fix: Improved the performance of atmospheric unpausing by ignoring updates on space turfs.
code: Subsystems are no longer allowed to sleep during their fire process.
del: Removes the delay from getting employment contracts out of the lawyers office thing. (No player facing changes, this was bugged anyway)
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
> There are still more changes that need to be made, am testing and pushing now

yep i just have the pr up for later i forgot to draft

**Comment by nednaZ** [comment]
Waiting on PowerfulBacon to finish, or at least be mostly finished with this before any test merging.

**Comment by PowerfulBacon** [comment]
Has a lot of dirty commits

**Comment by dwasint** [comment]
> Has a lot of dirty commits

yea i think  its due to me merging commits on github's website on my fork

**Comment by PowerfulBacon** [comment]
Tell me if the issue still happens, I have it testmerged on bee too and asked people to report if this happens. I'm not sure if this PR precicely fixes the issue, but it has a chance that it may fix it *somewhere* inside of it.

**Comment by dwasint** [comment]
> Tell me if the issue still happens, I have it testmerged on bee too and asked people to report if this happens. I'm not sure if this PR precicely fixes the issue, but it has a chance that it may fix it _somewhere_ inside of it.

Will do

**Comment by nednaZ** [comment]
Does this have relevance anymore?
If not, close it when you can.

**Comment by dwasint** [comment]
seeing as bee closed it don't think so

**Pull request closed without merging**
