### PR TITLE
Ghosts take on their parent appearance

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
ports: https://github.com/DaedalusDock/daedalusdock/pull/146

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: Ghosts now appear as your character
del: Most of the ghost preferences have been retired. BYOND members may still choose their rotation type!
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
https://github.com/DaedalusDock/daedalusdock/pull/173
https://github.com/DaedalusDock/daedalusdock/pull/176
https://github.com/DaedalusDock/daedalusdock/pull/210
took me a while to get it perfect

**Comment by wraith-54321** [comment]
I think it would be nice if this was a pref. While some people do like having their character I personally like the more simplified ghost design.

**Comment by nednaZ** [comment]
Honestly, I absolutely hate this.
Being stuck as a nude handcuffed corpse ghost isn't interesting in the slightest.
Plus it takes away one of the perks that Byond members get, so that's actually risking the long-term life of the game.

**Comment by dwasint** [comment]
overall reception of this is pretty poor, going to close this and look into fixing hair some other way

**Pull request closed without merging**
