### PR TITLE
The 3/4th-ing or how i changed another third of the code base

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Ports: https://github.com/pariahstation/Pariah-Station/pull/748 which is itself a port of 
https://github.com/hrzntal/horizon/pull/525
https://github.com/hrzntal/horizon/pull/888
also ports
https://github.com/pariahstation/Pariah-Station/pull/775 which is a port of
https://github.com/hrzntal/horizon/pull/646

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl: SabreML, ElorgRHG, Azarak ported here by dwasint
add: window shutters, radiation shutters
change: walls are now 3/4th
change: airlocks are now 3/4th
change: windows are now 3/4th
add: Added new (colorable) wall, low wall and window sprites.
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
credit original authors

**Comment by dwasint** [comment]
> credit original authors

yes yes i know i was going to do that when i eventually got to opening the pr, i'm not done yet so the body text ain't done either

**Comment by nednaZ** [comment]
> credit original authors

It is policy here that they do so, but this is a draft PR so it is unfinished.
You are not a part of our community in any form, so I ask that you don't needlessly leave unhelpful comments.

**Comment by Kapu1178** [comment]
> > credit original authors
> 
> It is policy here that they do so, but this is a draft PR so it is unfinished. You are not a part of our community in any form, so I ask that you don't needlessly leave unhelpful comments.

Code authorship credit isn't a community issue. If I see a PR in any repo that isn't creditting, I'll ask them to credit. The response of "It's a draft" is perfectly acceptable and it can easily be left at that.

**Pull request closed without merging**
