### PR TITLE
Vending Machine Tabs

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Adds tabs to vending machines to make em easier to navigate
Port of : https://github.com/tgstation/tgstation/pull/69076

## Why It's Good For The Game
User qol is nice

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

image

</details>
For the Future: More vending machines and new ones should be switched over to this
## Changelog

:cl:
add: tabs to vending machines
/:cl:

### CODE REVIEW

**Comment by JohnFulpWillard** [comment]
Can you credit the creator in the changelog, Mothblocks? https://github.com/tgstation/tgstation/pull/69076

**Comment by dwasint** [comment]
> Can you credit the creator in the changelog, Mothblocks? [tgstation/tgstation#69076](https://github.com/tgstation/tgstation/pull/69076)

whoops totally thought i had the pr in there my bad updating now

**Review by nednaZ — CHANGES_REQUESTED** [review]
The icons for the clothesmate tabs are missing, going to testmerge anyway.
Just need that fixed.

**Comment by nednaZ** [comment]
Contraband tab is not working.
Players are unable to buy the items.

Issue was a botanist trying to buy seeds from a hacked vendor.

**Comment by nednaZ** [comment]
Freebies on off-station vendors are not working, they still require cash.

**Review by nednaZ — APPROVED** [review]
Everything appears to be working as intended

**Pull request merged**
