### PR TITLE
possible fix for issue #604 - wrong/missing list len check

### PR DESCRIPTION
**Pull request by Xkeeper0**
will this fix it? who knows
but it will fix one part of the problem

# About The Pull Request

this fixes a bug. ordinarily i'd just push it to master

## Why It's Good For The Game

broke thing bad. fix thing good

## Testing Photographs and Procedure

as usual i did not test this at all

## Changelog

:cl:
fix: runtime in zclear preventing random_teleport_atom from working
/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
Tested the tool, still busted.

**Comment by Xkeeper0** [comment]
This PR still needs to be merged to fix the underlying subsystem runtiming.

Does it give any further errors or messages with this fix?

**Comment by nednaZ** [comment]
It does not, the tool just hangs on designating the area and leaves an overlay up.
No runtimes were seen

**Review by nednaZ — APPROVED** [review]
It's a decent enough bugfix by itself, so I am merging

**Pull request merged**
