### PR TITLE
City of Cogs has a smaller void now

### PR DESCRIPTION
**Pull request by DoctorSquishy**
# About The Pull Request
Reduces the void space of Reebe so the map size is 95x76 instead of 255x255 (refer to pictures for visual comparison)

## Why It's Good For The Game
Faster loading of Reebe

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

New [95x76]
image

Old [255x255]
image

</details>

## Changelog
No Player Facing Changes

### CODE REVIEW

**Comment by unit0016** [comment]
Fairly certain this will cause issues in one way or another honestly, since z-level size is meant to be consistent and all that jazz. Either there'll be REAL space surrounding Reebe or it'll do some funky behavior, but at the *very* least it'll always be centered on the southleft quadrant.

I think the solution isn't to give Reebe more or less space, but to get rid of Reebe outright.

**Comment by DoctorSquishy** [comment]
> 

Move Reebe to Centcom?

**Comment by unit0016** [comment]
> > 
> 
> Move Reebe to Centcom?

That'd be cool if we played around with the CC z-level to smush everything down - maybe we could change the Reebe void to black to hide the walls and void itself too to get away with compacting it even further? Just spitballing.

That being said we'd have to make the drone spawners only show up during clockcult for obvious reasons

**Comment by DoctorSquishy** [comment]
> > > 
> > 
> > 
> > Move Reebe to Centcom?
> 
> That'd be cool if we played around with the CC z-level to smush everything down - maybe we could change the Reebe void to black to hide the walls and void itself too to get away with compacting it even further? Just spitballing.
> 
> That being said we'd have to make the drone spawners only show up during clockcult for obvious reasons

Yeah I just tried it, there is some needed tweaks to get it all fully working and probably other bugs to squash. Most of it works just some weirdness with teleports to the station right now. I will work on that tomorrow.

**Review by nednaZ — APPROVED** [review]
Tested and the spawns appear to work as intended.
CPU usage is reduced, load time is improved and we can get clockies back on the menu.

For future reference, these were the issues I saw with moving it to the Centcom Z-level as a permanent thing:
Cogscarabs exist as ghost roles, need to move that to on gamemode trigger.
The Ark needs to be moved to gamemode trigger, or the clock cult event will fire upon shuttle arrival even without cultists.

**Pull request merged**
