### PR TITLE
Cat glove fix

### LINKED ISSUE #435: cat gloves front facing sprite is broken (and possibly side facing)
front facing is just 2 white rectangles on your arms, side facing looks weird but it might be fine

### PR DESCRIPTION
**Pull request by etherware-novice**
first commit so im very sorry if i messed up in any way i havent dont git much sorry!!!

# About The Pull Request

## Why It's Good For The Game

closes #435

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
:tweak: edited the catglove sprite
/:cl:

### CODE REVIEW

**Comment by etherware-novice** [comment]
aa! sorry i didnt see the autofill things!!

Why its good for the game - 
Fixing issues relating to visibility of the cat gloves

Testing photograps - 
None, sorry :( it is currently refusing to compile on my win8 machine but its just a sprite adjustment so it might not need that much i suppose?

Changelog - 
tweak: tweaked cat gloves

**Comment by nednaZ** [comment]
Okay, so for future reference:

You want to create a separate branch for every pull request.
Currently you are using: etherware-novice:master

You'll want to actually put what your PR changes in the changelog that exists by default as well as in the "About the Pull Request" section.

The title of your PR should be more descriptive, such as "Cat Glove Fix" in your case.

And if you are closing an Issue, make sure you put "closes #435", or whatever number, under "Why it's good for the game"
This will automatically connect this PR with an existing Issue.

**Comment by etherware-novice** [comment]
oh

so how do i edit the commit?

**Comment by dwasint** [comment]
> oh
> 
> so how do i edit the commit?

to change the pr click the 3 dots click edit

**Comment by nednaZ** [comment]
Your changelog needs to be within the :cl: tags, get rid of the extra unused ones there.
The "closes" part needs to just be "closes #435"

**Comment by etherware-novice** [comment]
is there anything else i would need to change here?

**Pull request merged**
