### PR TITLE
Smooth Movement [PORT]

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Adds TG's smooth movement system

Ports from: https://github.com/BeeStation/BeeStation-Hornet/pull/4540
https://github.com/yogstation13/Yogstation/pull/8132

## Why It's Good For The Game
Smoother movement is better for the eyes

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
changes:default fps to 60
changes:movement to look smoother
/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
If you're porting this off an existing PR, please link it in this PR.

**Comment by nednaZ** [comment]
This feels "weird"
Almost over-smoothed.

**Comment by dwasint** [comment]
> This feels "weird" Almost over-smoothed.

it feels like that to me on tg local aswell its probably related to local being way faster

**Review by nednaZ — APPROVED** [review]
No issues during testmerge

**Pull request merged**
