### PR TITLE
Fixes plasmaman security starting without envirohelms

### PR DESCRIPTION
**Pull request by pitaden**
I'm surprised this wasn't found sooner

# About The Pull Request

The departmental sec code didn't check if the helmet it was deleting was an envirohelm. This kills the plasmaman.
Plasmamen instead receive their departmental hat inside of their backpack.

## Why It's Good For The Game

It might be good to have plasmamen security not die on the arrivals shuttle.

## Testing Photographs and Procedure

<details>
<summary>Screenshot</summary>

image

</details>

## Changelog

:cl:
fix: security plasmamen now keep their envirohelm, and no longer burn to death after spawning
/:cl:

### CODE REVIEW

**Comment by pitaden** [comment]
gah, just realized I never pushed the second commit until now.

**Comment by lmenvs** [comment]
Good fix until I get plasmamen cowboy hats in

**Comment by nednaZ** [comment]
I'd like a more generalized solution in the future, for other species that may need special suits, but this is a good fix until there are actual plasmaman cowboy security hats.

**Comment by nednaZ** [comment]
Also, update your branch.
You're still in last month's code.

**Pull request merged**
