### PR TITLE
Fixes missing turf_decal tile icons

### PR DESCRIPTION
**Pull request by The-Black-Screen**
# About The Pull Request

This fixes the missing turf_decal tile icons in `icons/turf/decals.dmi` and moves the icons that were used to replace them into `monkestation/icons/turf/decals.dmi` for any potential future use.
One icon was renamed so it didn't override another one.

## Why It's Good For The Game

Missing turf_decal tile icons are available again.

## Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Fixed
Screenshot 2022-09-01 230032

Moved
Screenshot 2022-09-01 230129

</details>

## Changelog

:cl:
fix: The turf_decal tile icons now work again.
imageadd: The original tile_corner, tile_marquee, tile_side and tile_full from BeeStation.
/:cl:

### CODE REVIEW

**Comment by DoctorSquishy** [comment]
I kind of think that turf decals should not use the modular folder

**Comment by The-Black-Screen** [comment]
I am believe that there were already turf decals in there prior to me moving these ones.
If it is preferred that the ones that I moved are removed, then I'll remove them.

**Comment by DoctorSquishy** [comment]
I checked to see if this unintentionally removes any icons, but only the modular folder is actually using those, Everything looks good, I can always go back and move file paths around when I clean up the turfdecals and demodulatze that specific area. No need to worry about it currently actually, its good to have those icons fixed in the mean time

**Comment by nednaZ** [comment]
One issue I'm having is that this is on the Master branch rather than a specific branch made for this PR

**Comment by The-Black-Screen** [comment]
Would it be preferred that I close this, move it over to a branch and then do another pr?

**Comment by nednaZ** [comment]
That would be ideal.
It prevents any issues down the line having your master and our master be out of sync, should you make a PR that doesn't get added in.

**Comment by The-Black-Screen** [comment]
I'll go and do that then.

**Pull request closed without merging**
