### PR TITLE
Ass Blast USA

### PR DESCRIPTION
**Pull request by nednaZ**
## About The Pull Request

And yea, the great sord of fire rent the skies with great rending and sang us the thirteen songs of the posterior.

Lo, let it be seen that by the hand of the sord and the rear of the sord do we have more sound that descends from upon high the mountaintops and praise it with great praise.

Adds 13 new farts by Sord.

## Why It's Good For The Game

Is it?

## Changelog
:cl:
soundadd: 13 farts by Sord
/:cl:

### CODE REVIEW

**Comment by Zonespace27** [comment]
dear lord

**Comment by Sord213** [comment]
ass blast

**Comment by KoboldCommando** [comment]
An impromptu test showed that sord fart #20 makes an excellent sound effect for the infinite pie cannon.  Things are looking good for this PR!

**Comment by nednaZ** [comment]
After a year and a half of consideration, abandoning this codebase and a moment of madness, PR75 has been considered good enough to merge.
Now may we never touch this fork again.

**Pull request merged**
