### PR TITLE
Screentips Baby! [PORT from TG]

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Adds hoverable screentips from tg, lets you see what you hover over 
PRS used:
https://github.com/tgstation/tgstation/pull/56729
https://github.com/tgstation/tgstation/pull/65963
https://github.com/tgstation/tgstation/pull/63567

## Why It's Good For The Game
Makes the game easier for newer players by informing them of what they are looking at

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: screentips, lets you see what you are hovering over
/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
May want to look into the performance boost /tg/ did for this.
https://github.com/tgstation/tgstation/pull/63567

**Comment by dwasint** [comment]
> May want to look into the performance boost /tg/ did for this.
> [tgstation/tgstation#63567](https://github.com/tgstation/tgstation/pull/63567)

Alrighty, ported that aswell

**Review by nednaZ — COMMENTED** [review]
Looks fine. Will need some test merging on our next pass

**Comment by nednaZ** [comment]
No issues or lag seen over the past couple days.
Reminder to any future people looking at this PR, you can toggle off the screentips in preferences.

**Pull request merged**
