### PR TITLE
Ported Clothing And Resurrected Cosmetics

### PR DESCRIPTION
**Pull request by Salted-Zen**
# About The Pull Request

Ports some neat clothing from Citadel, Skyrat, TG. Also saves some cosmetics from the hellscape that is the unused Supporter/Donator meta store section and re-adds them to the regular meta store. Some of the new/resurrected stuff is available in vendors, but not all of it. All of it although can purchased in the meta coin store.

Sprites from these PRs
Driscoll, Decker, Saint, Morningstar, Phantom Outfits TG
https://github.com/tgstation/tgstation/pull/61123
Blood Red Pajamas TG
https://github.com/tgstation/tgstation/pull/49608
Cosmic Winter Coat CITADEL
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/9823
Kitsune Masks CITADEL
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15655

Codebases That I Pulled Sprites From That I Cant Find A Source PR For
Boat Cloak was taken from Skyrat
Polychromatic Cloak was taken from Citadel
Brown/Black Cowboy Boots taken from TG/Citadel
Heart Coat was taken from Citadel
Brass And Runed Winter Coats from Citadel
Wide Red Hat taken from Citadel
Polychromatic Cowboy Hat was taken from Citadel

Simian sprites are all made by LME and anything else (such as the conductive scarf, ian backpack, etc) are from within our files

If I have mis-sourced any of the sprites, or someone knows where a sprite used actually comes from, comment on it or something, I dug as best as I could, but maybe not hard enough.

## Why It's Good For The Game

This aims to add more exotic and interesting clothing/costumes to the meta store that people can save and spend coins on, while also adding new clothing to wear to vendors. Also it cleans out (most of) the unused stuff in the supporter meta store section that is leftover from bee, that way when the supporter meta coin store category becomes functional, it can be stocked with all new stuff. ALSO this fixes up some issues with modular things such as hoodies not changing states if put into modular.

oh also it adds more masks in the meta coin store, so you have no excuse now to buy the mime mask other than being a powergamer :)

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Uniforms
Suits
Shoes
Hats
Hooded
Masks
Necks
Backpacks
Full Decker Outfit
Decker Full
Full Driscoll Outfit
Driscoll Full
Full Morningstar Outfit
Morningstar Full
Full Phantom Outfit
Phantom Full
Full Saints Outfit
Saints full
The Heart Coat I Fucking Forgot To Screenshot With The Other Suits
TheHeartCloakIFuckingForgot

</details>

## Changelog

:cl:
add: Added a nice pile of new clothing / costumes to fill the meta store and costume / clothes vendor
tweak: (most) Donator exclusive clothing moved to other parts of the meta store
fix: Future hooded clothing in the modular folder will now change states when the hood is put up
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
i'd prefer if there was credit or atleast a link to the original pr's for clothing taken where applicable

**Comment by Salted-Zen** [comment]
> i'd prefer if there was credit or atleast a link to the original pr's for clothing taken where applicable

I'll see what I can do when possible

**Comment by dwasint** [comment]
last thing, add to the changelog that donator exclusive clothing was moved to other catagories

**Comment by Salted-Zen** [comment]
Other than the known issues, everything should be set to go!

**Comment by dwasint** [comment]
https://r67.cooltext.com/rendered/cooltext431790346425110.gif

**Comment by Salted-Zen** [comment]
:O

**Pull request merged**
