### PR TITLE
Mimic eye upgrade

### PR DESCRIPTION
**Pull request by Oricana-16**
# About The Pull Request

Mimics get x-ray, letting them hide better from people.

## Why It's Good For The Game

I have reasons both for and against this.
They'll be able to hide a lot and ventcrawl around a lot better, which is good for what I think they should be.
But, hiding from mimics becomes impossible, ruining any moments like that, if any would happen in the first place.

Because im so split on it, I just made it a PR and you can merge or close it depending on what fits more with your idea of mimics. Alternatively, it can be a part of one of the evolved mimic's abilities instead of a base thing.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: mimics can see mobs through walls.
/:cl:

### CODE REVIEW

**Comment by lmenvs** [comment]
you could give them a smaller vision range in addition to xray to balance it out maybe?

**Comment by Oricana-16** [comment]
Took a bit to look and i could not find out how I'd do that. I also think that'd be like counteractive to itself and further from what I think of it, since they'd see less and have a harder time hiding on time.

**Comment by lmenvs** [comment]
what about making xray vision an ability with a cooldown?

**Comment by Oricana-16** [comment]
I think if I did an ability that'd be for sure an evolution, so i'll wait on zan to decide on what prefers

**Comment by nednaZ** [comment]
Is this full X-Ray, or thermal style vision?
I'm in favor of thermal, but not full X-Ray

**Comment by Oricana-16** [comment]
Thermal vision. They can only see other mobs through walls.

**Review by nednaZ — APPROVED** [review]
Looks good to me.

**Pull request merged**
