### PR TITLE
Syndicate announcer station trait!

### PR DESCRIPTION
**Pull request by etherware-novice**
# About The Pull Request
The syndicate, using their powerful mercenaries and advanced tech, have managed to hijack centcom's announcement machine, and now they're gonna run it how they want!

## Why It's Good For The Game
More variety is fun and it makes sense in universe cause syndicate

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
:soundadd: added sound bytes for syndi announcer
:add: added station trait 
/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
I legitimately can't understand half of the lines being spoken.
The echo effect and text to speech isn't very good.

**Comment by etherware-novice** [comment]
oh dang

**Comment by Zonespace27** [comment]
> I legitimately can't understand half of the lines being spoken. The echo effect and text to speech isn't very good.

Gotta agree with zanden here, also, where were these sourced from?

**Comment by etherware-novice** [comment]
> 

sourced from this tts program called espeak

**Pull request closed without merging**
