### PR TITLE
Adds "No Soul" quirk

### PR DESCRIPTION
**Pull request by KoboldCommando**
# About The Pull Request

As requested by Ook on stream, 12/30/22.  The "No Soul" quirk causes airlocks to not recognize you automatically, you can't bump-open them and instead have to manually click all of them.  A minor inconvenience but a constant one.

The point value of 1 may be too high, but giving it a point value of 0 is a bit weird.  Adjustments could be figured out.

## Why It's Good For The Game

More fun and flavorful quirks.  Hopefully this one can be expanded going forward, too!

## Changelog

:cl:
add: A new quirk, "No Soul", in case you love opening doors but don't want to play AI
/:cl:

### CODE REVIEW

**Comment by dwasint** [comment]
1 point is good imo, it has a big enough disadvantage in fights to justify it imo

**Review by dwasint — APPROVED** [review]

**Comment by dwasint** [comment]
i'm almost tempted to merge this as it looks like no errors but i will tm it for a few rounds when i get the power to do so.

**Comment by Zonespace27** [comment]
Should force their hair to be ginger

**Comment by dwasint** [comment]
Looks good no issues thus far will merge

**Pull request merged**
