### PR TITLE
Adds Ant and Decomposing [PORT of TG]

### PR DESCRIPTION
**Pull request by dwasint**
# About The Pull Request
Ports:
https://github.com/tgstation/tgstation/pull/64786
https://github.com/tgstation/tgstation/pull/60392
https://github.com/tgstation/tgstation/pull/65284
https://github.com/tgstation/tgstation/pull/65409
https://github.com/tgstation/tgstation/pull/62496
https://github.com/tgstation/tgstation/pull/59634

## Why It's Good For The Game
Makes food perish meaning you need to store food off the floor, no more being gross

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: Due to a leak in Nanotrasen Brand Ant Farms during shipping, a large influx of space-ants have been inadvertently dumped onto every Nanotrasen station. Don't go leaving food around too long, and please be sure to watch your step, we're pretty sure they bite...
imageadd: New giant ant sprite by Doshmobile
/:cl:

### CODE REVIEW

**Review by nednaZ — APPROVED** [review]
Looks good to me, but I will want to test merge before committing to it.

**Comment by dwasint** [comment]
sweet

**Comment by nednaZ** [comment]
Currently, ants appear to do too much potential damage.
The self-damage from scratching and the damage from walking over them stacks quite fast

**Comment by nednaZ** [comment]
No further issues seen during test merging

**Pull request merged**
