### PR TITLE
Use operating computers while lying down

### PR DESCRIPTION
**Pull request by DoctorSquishy**
# About The Pull Request
Allows the user to use the operating computer while lying down. 
The minor inconvenience of laying down is negated anyways by the wiki. Less demand on looking up things on the wiki, the better.

closes https://github.com/Monkestation/MonkeStation/issues/263

## Changelog

:cl:

tweak: You can use operating computers while lying down, just try not to get blood all over the keyboard

/:cl:

### CODE REVIEW

**Comment by nednaZ** [comment]
Tip for the future.
To close an issue with a PR, put "closes #???" in the description.
As in: closes #263

**Comment by DoctorSquishy** [comment]
> Tip for the future. To close an issue with a PR, put "closes #???" in the description. As in: closes #263
Thanks, I'll be sure to do that when putting out fixes for bugs

**Comment by nednaZ** [comment]
This actually appears to make it so ALL computers can be used laying down.

**Review by nednaZ — CHANGES_REQUESTED** [review]
This allows you to half-use all computers while laying down.
While you can view the screen, you cannot actually use any of the buttons.
This includes security cameras, where you're unable to see the camera view until you can press a button.

It seems a bit too broad of a change that introduces a large amount of new hidden bugs and interaction inconsistencies.
You need to find a way to have it work just for the operating computer.

**Comment by DoctorSquishy** [comment]
> This allows you to half-use all computers while laying down. While you can view the screen, you cannot actually use any of the buttons. This includes security cameras, where you're unable to see the camera view until you can press a button.
> 
> It seems a bit too broad of a change that introduces a large amount of new hidden bugs and interaction inconsistencies. You need to find a way to have it work just for the operating computer.

Made the change in operating computer specifically this time. I was able to sync research and click around the op computer while lying down on the operating table

**Review by nednaZ — APPROVED** [review]
Functions as intended.

**Pull request merged**
