### PR TITLE
5 Piping Layer Port of Port

### PR DESCRIPTION
**Pull request by DoctorSquishy**
# About The Pull Request
Increases amount of piping layers to 5 (excludes Heat Exchanges pipes)

Note: Mappers should not use layers 1 & 5

## Why It's Good For The Game
5 layers will help with future atmos complex builds plus BeeStation and TG has it so I figure it is good to have it implemented as well.

## Testing Photographs and Procedure

<details>
<summary>Screenshots</summary>

image

image

</details>

## PR References
Main PR port from BeeStation:
- https://github.com/BeeStation/BeeStation-Hornet/pull/6039

- https://github.com/tgstation/tgstation/pull/53278
- https://github.com/tgstation/tgstation/pull/53382
- https://github.com/tgstation/tgstation/pull/53829
- https://github.com/tgstation/tgstation/pull/57273

## Changelog
:cl:  DoctorSquishy, lordScrubling, Ghilker, nicbn
add: atmospherics now has 2 additional layers; excludes HE pipes
add: multi-z adapters can now be placed with RPDs
tweak: layer manifold has its volume increased from 280L to 350 to compensate for increase in layers
tweak: Heat Exchange pipes are slightly lighter to improve contrast on space background
fix: Monkey Mapper icon state
/:cl:

### CODE REVIEW

**Comment by DoctorSquishy** [comment]
Once this is merged I'll do the PR for the multi-z improvements

**Comment by nednaZ** [comment]
So here's my immediate concern.
Why does this modify the base maps?

How badly is this going to hurt our current map changes?

**Comment by DoctorSquishy** [comment]
> So here's my immediate concern. Why does this modify the base maps?
> 
> How badly is this going to hurt our current map changes?

It renames the pipe layers for distro and their scrubbers and vents from layers 1 and 3 to 2 and 4

**Comment by DoctorSquishy** [comment]
I would wait til HoleStation is merged so I can update that one too

**Review by nednaZ — COMMENTED** [review]
I'm not seeing any obvious issues with it, but we'll still be test merging this.

**Review by nednaZ — APPROVED** [review]
Zero issues have been found after a couple days of test merging.

**Pull request merged**
