### PR TITLE
Span Macros [PORT]

### PR DESCRIPTION
**Pull request by DoctorSquishy**
# About The Pull Request
 Separate PR for actually changing spans over. Yay or Nay? Also please read through the BeeStation PR thread to see some of the arguments against it that a few of their coders had.

Adds Span Macros and eventually a refactor for changing DM code into said span macros

This PR adds macros in the format of `span_CLASS(CONTENT)`, for example:
```DM
span_warning("It looks slightly dented")
```
As opposed to:
```DM
<span class='warning'>It looks slightly dented</span>
```
## Why It's Good For The Game
Code improvement with writing out spans, and porting from TG. Spans the DM way are a pain to write and look at.

### PR REFERENCES:
- Widespread code changes based on:
https://github.com/tgstation/tgstation/pull/59645
- Macros based on:
https://github.com/tgstation/tgstation/pull/59685
- BeeStation's Closed PR with debating on the subject with some Tick Usage notes:
https://github.com/BeeStation/BeeStation-Hornet/pull/4971

## Changelog

:cl:
refactor: Refactors spans in code to be able to use macros. If you spot any new broken messages in chat, having missing text, broken tags in the message, or being formatted wrong, make sure to report them.
/:cl:

### CODE REVIEW

**Comment by WonderPsycho** [comment]
oh god this gives me fear, cause i fear having to work on E-N again, but this time i need to replace the span procs with the new ones, hopefully it won't be too hard to rework those span proc and don't give me issues again like when i was near being done with working on E-N, and it took like 1 and a half months to try and get him done and stuff

**Comment by DoctorSquishy** [comment]
> oh god this gives me fear, cause i fear having to work on E-N again, but this time i need to replace the span procs with the new ones, hopefully it won't be too hard to rework those span proc and don't give me issues again like when i was near being done with working on E-N, and it took like 1 and a half months to try and get him done and stuff

DM spans sill work even with this implemented. It just adds new macros that can read this code format `span_warning("It looks slightly dented")` and understand it as this `<span class='warning'>It looks slightly dented</span>` still

**Comment by WonderPsycho** [comment]
> DM spans sill work even with this implemented. It just adds new macros that can read this code format `span_warning("It looks slightly dented")` and understand it as this `<span class='warning'>It looks slightly dented</span>` still

oh nevermind, i thought this was gonna completely replace span procs and turn them into span proc macros, my misunderstanding, I still like this, and now i like even more now knowing this

**Comment by polygoblyn** [comment]
If you do end up replacing all of the spans, probably have a chat with Merlin. They had set up a script to replace bitfields before and may save you considerable amount of time

**Comment by DoctorSquishy** [comment]
> If you do end up replacing all of the spans, probably have a chat with Merlin. They had set up a script to replace bitfields before and may save you considerable amount of time

That's a good idea, could be a good learning experience too. For now I think just merging this addition first would be a good idea and then later add a PR to change spans so it is easier for the maintainer

**Review by nednaZ — APPROVED** [review]
Looks good to me.
I like this simply because it has all of the spans right in one place.

**Comment by nednaZ** [comment]
In the specific case of slowdown that was noted by Beestation, we won't be converting our old spans to this.
We will be using this mainly for ports.

**Pull request merged**
