### PR TITLE
Add Plating to Metal Foams [QoL] [PORT]

### PR DESCRIPTION
**Pull request by DoctorSquishy**
# About The Pull Request

Metal foam now acts as a "girder" and can have metal sheets applied to it to build a wall. Also you can stand on it when it is on a Z-Level below.  The metal foam also works with the smooth icons on current walls and have their own base icons

Each metal foam type deconstructs back into itself; however are constructed at different speeds, sliced apart at different speeds, and hardness for hulk smashing.
iron_foam_base >Basically Normal Wall >metal_foam_base > resin_foam_base

Metal Foam QoL Port from TG:
https://github.com/tgstation/tgstation/pull/64386
https://github.com/tgstation/tgstation/pull/64553
https://github.com/tgstation/tgstation/pull/66184

## Why It's Good For The Game
Should help with rebuilding breaches without an RCD and makes metal foam and resins more effective by cutting a rebuilding step down. While we may not use Z-Levels too much currently, being able to walk on the metal foam when it is below makes more sense then falling into a large amount and suddenly you need to break a path through to get out of it.

## Testing Photographs and Procedure

<details>
<summary>Screenshots&Videos</summary>

New icons for Metal Foam Structures:
image

image

image

image

image

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

## Changelog

:cl:
add: Metal foam structures can now be used as a girder to finish building walls.
imageadd: Added icons for the different Metal Foam Walls when plated
fix: metal foam now blocks you from falling down a z-level if it's below you
fix: Iron walls built on top of metal foam will produce metal foam instead of a girder when decon'd.
refactor: The slicing duration for walls in walls.dm are now clear as Seconds
/:cl:

### CODE REVIEW

**Comment by DoctorSquishy** [comment]
I expanded upon the foamed metal walls, although its use will probably be uncommon, there is some differences in quality when using the three different metal foams

**Comment by DoctorSquishy** [comment]
Actually I think I am going to make icon_states for these walls

**Review by nednaZ — APPROVED** [review]
Good changes.
I like the new foam wall sprites as well, could see them used in actual mapping.

**Comment by DoctorSquishy** [comment]
> Good changes. I like the new foam wall sprites as well, could see them used in actual mapping.

I'll probably tweak the smooth overlays a bit more to make them appear plated on, maybe a weekend thing if I get stuck on something

**Pull request merged**
